// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: idl/task.proto

package task

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskID        int64                  `protobuf:"varint,1,opt,name=taskID,proto3" json:"taskID,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_idl_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_idl_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_idl_task_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetTaskID() int64 {
	if x != nil {
		return x.TaskID
	}
	return 0
}

func (x *Task) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Task) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Task) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Task) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Task) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type AddTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTaskRequest) Reset() {
	*x = AddTaskRequest{}
	mi := &file_idl_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTaskRequest) ProtoMessage() {}

func (x *AddTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTaskRequest.ProtoReflect.Descriptor instead.
func (*AddTaskRequest) Descriptor() ([]byte, []int) {
	return file_idl_task_proto_rawDescGZIP(), []int{1}
}

func (x *AddTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddTaskRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type AddTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Task                  `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTaskResponse) Reset() {
	*x = AddTaskResponse{}
	mi := &file_idl_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTaskResponse) ProtoMessage() {}

func (x *AddTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTaskResponse.ProtoReflect.Descriptor instead.
func (*AddTaskResponse) Descriptor() ([]byte, []int) {
	return file_idl_task_proto_rawDescGZIP(), []int{2}
}

func (x *AddTaskResponse) GetData() *Task {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_idl_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_idl_task_proto_rawDescGZIP(), []int{3}
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Task                `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_idl_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_idl_task_proto_rawDescGZIP(), []int{4}
}

func (x *ListTasksResponse) GetData() []*Task {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskID        int64                  `protobuf:"varint,1,opt,name=taskID,proto3" json:"taskID,omitempty"`
	Content       *string                `protobuf:"bytes,2,opt,name=content,proto3,oneof" json:"content,omitempty"`
	Title         *string                `protobuf:"bytes,3,opt,name=title,proto3,oneof" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskRequest) Reset() {
	*x = UpdateTaskRequest{}
	mi := &file_idl_task_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRequest) ProtoMessage() {}

func (x *UpdateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_task_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return file_idl_task_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateTaskRequest) GetTaskID() int64 {
	if x != nil {
		return x.TaskID
	}
	return 0
}

func (x *UpdateTaskRequest) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *UpdateTaskRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

type UpdateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskResponse) Reset() {
	*x = UpdateTaskResponse{}
	mi := &file_idl_task_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskResponse) ProtoMessage() {}

func (x *UpdateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_task_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskResponse.ProtoReflect.Descriptor instead.
func (*UpdateTaskResponse) Descriptor() ([]byte, []int) {
	return file_idl_task_proto_rawDescGZIP(), []int{6}
}

type UpdateTaskStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskID        int64                  `protobuf:"varint,1,opt,name=taskID,proto3" json:"taskID,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskStatusRequest) Reset() {
	*x = UpdateTaskStatusRequest{}
	mi := &file_idl_task_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskStatusRequest) ProtoMessage() {}

func (x *UpdateTaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_task_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_idl_task_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTaskStatusRequest) GetTaskID() int64 {
	if x != nil {
		return x.TaskID
	}
	return 0
}

func (x *UpdateTaskStatusRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpdateTaskStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskStatusResponse) Reset() {
	*x = UpdateTaskStatusResponse{}
	mi := &file_idl_task_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskStatusResponse) ProtoMessage() {}

func (x *UpdateTaskStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_task_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateTaskStatusResponse) Descriptor() ([]byte, []int) {
	return file_idl_task_proto_rawDescGZIP(), []int{8}
}

type RecycleBinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecycleBinRequest) Reset() {
	*x = RecycleBinRequest{}
	mi := &file_idl_task_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecycleBinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecycleBinRequest) ProtoMessage() {}

func (x *RecycleBinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_task_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecycleBinRequest.ProtoReflect.Descriptor instead.
func (*RecycleBinRequest) Descriptor() ([]byte, []int) {
	return file_idl_task_proto_rawDescGZIP(), []int{9}
}

type RecycleBinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Task                `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecycleBinResponse) Reset() {
	*x = RecycleBinResponse{}
	mi := &file_idl_task_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecycleBinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecycleBinResponse) ProtoMessage() {}

func (x *RecycleBinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_task_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecycleBinResponse.ProtoReflect.Descriptor instead.
func (*RecycleBinResponse) Descriptor() ([]byte, []int) {
	return file_idl_task_proto_rawDescGZIP(), []int{10}
}

func (x *RecycleBinResponse) GetData() []*Task {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_idl_task_proto protoreflect.FileDescriptor

const file_idl_task_proto_rawDesc = "" +
	"\n" +
	"\x0eidl/task.proto\x12\x04task\"\xa4\x01\n" +
	"\x04Task\x12\x16\n" +
	"\x06taskID\x18\x01 \x01(\x03R\x06taskID\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\"@\n" +
	"\x0eAddTaskRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"1\n" +
	"\x0fAddTaskResponse\x12\x1e\n" +
	"\x04data\x18\x01 \x01(\v2\n" +
	".task.TaskR\x04data\"\x12\n" +
	"\x10ListTasksRequest\"3\n" +
	"\x11ListTasksResponse\x12\x1e\n" +
	"\x04data\x18\x01 \x03(\v2\n" +
	".task.TaskR\x04data\"{\n" +
	"\x11UpdateTaskRequest\x12\x16\n" +
	"\x06taskID\x18\x01 \x01(\x03R\x06taskID\x12\x1d\n" +
	"\acontent\x18\x02 \x01(\tH\x00R\acontent\x88\x01\x01\x12\x19\n" +
	"\x05title\x18\x03 \x01(\tH\x01R\x05title\x88\x01\x01B\n" +
	"\n" +
	"\b_contentB\b\n" +
	"\x06_title\"\x14\n" +
	"\x12UpdateTaskResponse\"I\n" +
	"\x17UpdateTaskStatusRequest\x12\x16\n" +
	"\x06taskID\x18\x01 \x01(\x03R\x06taskID\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"\x1a\n" +
	"\x18UpdateTaskStatusResponse\"\x13\n" +
	"\x11RecycleBinRequest\"4\n" +
	"\x12RecycleBinResponse\x12\x1e\n" +
	"\x04data\x18\x01 \x03(\v2\n" +
	".task.TaskR\x04data2\xd8\x02\n" +
	"\vTaskService\x126\n" +
	"\aAddTask\x12\x14.task.AddTaskRequest\x1a\x15.task.AddTaskResponse\x12<\n" +
	"\tListTasks\x12\x16.task.ListTasksRequest\x1a\x17.task.ListTasksResponse\x12?\n" +
	"\n" +
	"UpdateTask\x12\x17.task.UpdateTaskRequest\x1a\x18.task.UpdateTaskResponse\x12Q\n" +
	"\x10UpdateTaskStatus\x12\x1d.task.UpdateTaskStatusRequest\x1a\x1e.task.UpdateTaskStatusResponse\x12?\n" +
	"\n" +
	"RecycleBin\x12\x17.task.RecycleBinRequest\x1a\x18.task.RecycleBinResponseB\aZ\x05/taskb\x06proto3"

var (
	file_idl_task_proto_rawDescOnce sync.Once
	file_idl_task_proto_rawDescData []byte
)

func file_idl_task_proto_rawDescGZIP() []byte {
	file_idl_task_proto_rawDescOnce.Do(func() {
		file_idl_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_idl_task_proto_rawDesc), len(file_idl_task_proto_rawDesc)))
	})
	return file_idl_task_proto_rawDescData
}

var file_idl_task_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_idl_task_proto_goTypes = []any{
	(*Task)(nil),                     // 0: task.Task
	(*AddTaskRequest)(nil),           // 1: task.AddTaskRequest
	(*AddTaskResponse)(nil),          // 2: task.AddTaskResponse
	(*ListTasksRequest)(nil),         // 3: task.ListTasksRequest
	(*ListTasksResponse)(nil),        // 4: task.ListTasksResponse
	(*UpdateTaskRequest)(nil),        // 5: task.UpdateTaskRequest
	(*UpdateTaskResponse)(nil),       // 6: task.UpdateTaskResponse
	(*UpdateTaskStatusRequest)(nil),  // 7: task.UpdateTaskStatusRequest
	(*UpdateTaskStatusResponse)(nil), // 8: task.UpdateTaskStatusResponse
	(*RecycleBinRequest)(nil),        // 9: task.RecycleBinRequest
	(*RecycleBinResponse)(nil),       // 10: task.RecycleBinResponse
}
var file_idl_task_proto_depIdxs = []int32{
	0,  // 0: task.AddTaskResponse.data:type_name -> task.Task
	0,  // 1: task.ListTasksResponse.data:type_name -> task.Task
	0,  // 2: task.RecycleBinResponse.data:type_name -> task.Task
	1,  // 3: task.TaskService.AddTask:input_type -> task.AddTaskRequest
	3,  // 4: task.TaskService.ListTasks:input_type -> task.ListTasksRequest
	5,  // 5: task.TaskService.UpdateTask:input_type -> task.UpdateTaskRequest
	7,  // 6: task.TaskService.UpdateTaskStatus:input_type -> task.UpdateTaskStatusRequest
	9,  // 7: task.TaskService.RecycleBin:input_type -> task.RecycleBinRequest
	2,  // 8: task.TaskService.AddTask:output_type -> task.AddTaskResponse
	4,  // 9: task.TaskService.ListTasks:output_type -> task.ListTasksResponse
	6,  // 10: task.TaskService.UpdateTask:output_type -> task.UpdateTaskResponse
	8,  // 11: task.TaskService.UpdateTaskStatus:output_type -> task.UpdateTaskStatusResponse
	10, // 12: task.TaskService.RecycleBin:output_type -> task.RecycleBinResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_idl_task_proto_init() }
func file_idl_task_proto_init() {
	if File_idl_task_proto != nil {
		return
	}
	file_idl_task_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_idl_task_proto_rawDesc), len(file_idl_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_idl_task_proto_goTypes,
		DependencyIndexes: file_idl_task_proto_depIdxs,
		MessageInfos:      file_idl_task_proto_msgTypes,
	}.Build()
	File_idl_task_proto = out.File
	file_idl_task_proto_goTypes = nil
	file_idl_task_proto_depIdxs = nil
}
