// Code generated by protoc-gen-go-zrpc. DO NOT EDIT.
// versrions:
// -protoc-gen-go-zrpc v0.1.0
// -protoc             v6.32.1

package task

import (
	context "context"
	fmt "fmt"
	zrpc "github.com/crazyfrankie/zrpc"
)

const (
	TaskService_AddTask_FullMethodName          = "task.TaskService/AddTask"
	TaskService_ListTasks_FullMethodName        = "task.TaskService/ListTasks"
	TaskService_UpdateTask_FullMethodName       = "task.TaskService/UpdateTask"
	TaskService_UpdateTaskStatus_FullMethodName = "task.TaskService/UpdateTaskStatus"
	TaskService_RecycleBin_FullMethodName       = "task.TaskService/RecycleBin"
)

// TaskServiceClient is the API for TaskService service.

type TaskServiceClient interface {
	AddTask(ctx context.Context, in *AddTaskRequest) (*AddTaskResponse, error)
	ListTasks(ctx context.Context, in *ListTasksRequest) (*ListTasksResponse, error)
	UpdateTask(ctx context.Context, in *UpdateTaskRequest) (*UpdateTaskResponse, error)
	UpdateTaskStatus(ctx context.Context, in *UpdateTaskStatusRequest) (*UpdateTaskStatusResponse, error)
	RecycleBin(ctx context.Context, in *RecycleBinRequest) (*RecycleBinResponse, error)
}

type taskServiceClient struct {
	cli zrpc.ClientInterface
}

func NewTaskServiceClient(cc zrpc.ClientInterface) TaskServiceClient {
	return &taskServiceClient{cc}
}

func (c *taskServiceClient) AddTask(ctx context.Context, in *AddTaskRequest) (*AddTaskResponse, error) {
	out := new(AddTaskResponse)
	err := c.cli.Invoke(ctx, TaskService_AddTask_FullMethodName, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) ListTasks(ctx context.Context, in *ListTasksRequest) (*ListTasksResponse, error) {
	out := new(ListTasksResponse)
	err := c.cli.Invoke(ctx, TaskService_ListTasks_FullMethodName, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) UpdateTask(ctx context.Context, in *UpdateTaskRequest) (*UpdateTaskResponse, error) {
	out := new(UpdateTaskResponse)
	err := c.cli.Invoke(ctx, TaskService_UpdateTask_FullMethodName, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) UpdateTaskStatus(ctx context.Context, in *UpdateTaskStatusRequest) (*UpdateTaskStatusResponse, error) {
	out := new(UpdateTaskStatusResponse)
	err := c.cli.Invoke(ctx, TaskService_UpdateTaskStatus_FullMethodName, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) RecycleBin(ctx context.Context, in *RecycleBinRequest) (*RecycleBinResponse, error) {
	out := new(RecycleBinResponse)
	err := c.cli.Invoke(ctx, TaskService_RecycleBin_FullMethodName, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskServiceServer is the server API for TaskService service
// All implementations must embed UnimplementedTaskServiceServer
// for forward compatibility.
type TaskServiceServer interface {
	AddTask(context.Context, *AddTaskRequest) (*AddTaskResponse, error)
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error)
	UpdateTask(context.Context, *UpdateTaskRequest) (*UpdateTaskResponse, error)
	UpdateTaskStatus(context.Context, *UpdateTaskStatusRequest) (*UpdateTaskStatusResponse, error)
	RecycleBin(context.Context, *RecycleBinRequest) (*RecycleBinResponse, error)
	mustEmbedUnimplementedTaskServiceServer()
}

// UnimplementedTaskServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskServiceServer struct{}

func (UnimplementedTaskServiceServer) AddTask(context.Context, *AddTaskRequest) (*AddTaskResponse, error) {
	return nil, fmt.Errorf("method AddTask not implemented")
}
func (UnimplementedTaskServiceServer) ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error) {
	return nil, fmt.Errorf("method ListTasks not implemented")
}
func (UnimplementedTaskServiceServer) UpdateTask(context.Context, *UpdateTaskRequest) (*UpdateTaskResponse, error) {
	return nil, fmt.Errorf("method UpdateTask not implemented")
}
func (UnimplementedTaskServiceServer) UpdateTaskStatus(context.Context, *UpdateTaskStatusRequest) (*UpdateTaskStatusResponse, error) {
	return nil, fmt.Errorf("method UpdateTaskStatus not implemented")
}
func (UnimplementedTaskServiceServer) RecycleBin(context.Context, *RecycleBinRequest) (*RecycleBinResponse, error) {
	return nil, fmt.Errorf("method RecycleBin not implemented")
}
func (UnimplementedTaskServiceServer) mustEmbedUnimplementedTaskServiceServer() {}
func (UnimplementedTaskServiceServer) testEmbeddedByValue()                     {}

// UnsafeTaskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskServiceServer will
// result in compilation errors.
type UnsafeTaskServiceServer interface {
	mustEmbedUnimplementedTaskServiceServer()
}

func RegisterTaskServiceServer(s zrpc.ServiceRegistrar, srv TaskServiceServer) {
	// If the following call panics, it indicates UnimplementedTaskServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskService_ServiceDesc, srv)
}

func _TaskService_AddTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, middleware zrpc.ServerMiddleware) (interface{}, error) {
	in := new(AddTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if middleware == nil {
		return srv.(TaskServiceServer).AddTask(ctx, in)
	}
	info := &zrpc.ServerInfo{
		Server:     srv,
		FullMethod: TaskService_AddTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).AddTask(ctx, req.(*AddTaskRequest))
	}
	return middleware(ctx, in, info, handler)
}

func _TaskService_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, middleware zrpc.ServerMiddleware) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if middleware == nil {
		return srv.(TaskServiceServer).ListTasks(ctx, in)
	}
	info := &zrpc.ServerInfo{
		Server:     srv,
		FullMethod: TaskService_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).ListTasks(ctx, req.(*ListTasksRequest))
	}
	return middleware(ctx, in, info, handler)
}

func _TaskService_UpdateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, middleware zrpc.ServerMiddleware) (interface{}, error) {
	in := new(UpdateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if middleware == nil {
		return srv.(TaskServiceServer).UpdateTask(ctx, in)
	}
	info := &zrpc.ServerInfo{
		Server:     srv,
		FullMethod: TaskService_UpdateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).UpdateTask(ctx, req.(*UpdateTaskRequest))
	}
	return middleware(ctx, in, info, handler)
}

func _TaskService_UpdateTaskStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, middleware zrpc.ServerMiddleware) (interface{}, error) {
	in := new(UpdateTaskStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if middleware == nil {
		return srv.(TaskServiceServer).UpdateTaskStatus(ctx, in)
	}
	info := &zrpc.ServerInfo{
		Server:     srv,
		FullMethod: TaskService_UpdateTaskStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).UpdateTaskStatus(ctx, req.(*UpdateTaskStatusRequest))
	}
	return middleware(ctx, in, info, handler)
}

func _TaskService_RecycleBin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, middleware zrpc.ServerMiddleware) (interface{}, error) {
	in := new(RecycleBinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if middleware == nil {
		return srv.(TaskServiceServer).RecycleBin(ctx, in)
	}
	info := &zrpc.ServerInfo{
		Server:     srv,
		FullMethod: TaskService_RecycleBin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).RecycleBin(ctx, req.(*RecycleBinRequest))
	}
	return middleware(ctx, in, info, handler)
}

// TaskService_ServiceDesc is the zrpc.ServiceDesc for TaskService service.
// It's only intended for direct use withzrpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskService_ServiceDesc = zrpc.ServiceDesc{
	ServiceName: "task.TaskService",
	HandlerType: (*TaskServiceServer)(nil),
	Methods: []zrpc.MethodDesc{
		{
			MethodName: "AddTask",
			Handler:    _TaskService_AddTask_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _TaskService_ListTasks_Handler,
		},
		{
			MethodName: "UpdateTask",
			Handler:    _TaskService_UpdateTask_Handler,
		},
		{
			MethodName: "UpdateTaskStatus",
			Handler:    _TaskService_UpdateTaskStatus_Handler,
		},
		{
			MethodName: "RecycleBin",
			Handler:    _TaskService_RecycleBin_Handler,
		},
	},
	Metadata: "idl/task.proto",
}
