// Code generated by protoc-gen-go-zrpc. DO NOT EDIT.
// versrions:
// -protoc-gen-go-zrpc v0.1.0
// -protoc             v6.32.1

package user

import (
	context "context"
	fmt "fmt"
	zrpc "github.com/crazyfrankie/zrpc"
)

const (
	UserService_Register_FullMethodName      = "user.UserService/Register"
	UserService_Login_FullMethodName         = "user.UserService/Login"
	UserService_GetUserInfo_FullMethodName   = "user.UserService/GetUserInfo"
	UserService_UpdateAvatar_FullMethodName  = "user.UserService/UpdateAvatar"
	UserService_ResetPassword_FullMethodName = "user.UserService/ResetPassword"
	UserService_Logout_FullMethodName        = "user.UserService/Logout"
	UserService_RefreshToken_FullMethodName  = "user.UserService/RefreshToken"
)

// UserServiceClient is the API for UserService service.

type UserServiceClient interface {
	Register(ctx context.Context, in *RegisterRequest) (*RegisterResponse, error)
	Login(ctx context.Context, in *LoginRequest) (*LoginResponse, error)
	GetUserInfo(ctx context.Context, in *GetUserInfoRequest) (*GetUserInfoResponse, error)
	UpdateAvatar(ctx context.Context, in *UpdateAvatarRequest) (*UpdateAvatarResponse, error)
	ResetPassword(ctx context.Context, in *ResetPasswordRequest) (*ResetPasswordResponse, error)
	Logout(ctx context.Context, in *LogoutRequest) (*LogoutResponse, error)
	RefreshToken(ctx context.Context, in *RefreshTokenRequest) (*RefreshTokenResponse, error)
}

type userServiceClient struct {
	cli zrpc.ClientInterface
}

func NewUserServiceClient(cc zrpc.ClientInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Register(ctx context.Context, in *RegisterRequest) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cli.Invoke(ctx, UserService_Register_FullMethodName, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Login(ctx context.Context, in *LoginRequest) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cli.Invoke(ctx, UserService_Login_FullMethodName, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserInfo(ctx context.Context, in *GetUserInfoRequest) (*GetUserInfoResponse, error) {
	out := new(GetUserInfoResponse)
	err := c.cli.Invoke(ctx, UserService_GetUserInfo_FullMethodName, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateAvatar(ctx context.Context, in *UpdateAvatarRequest) (*UpdateAvatarResponse, error) {
	out := new(UpdateAvatarResponse)
	err := c.cli.Invoke(ctx, UserService_UpdateAvatar_FullMethodName, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ResetPassword(ctx context.Context, in *ResetPasswordRequest) (*ResetPasswordResponse, error) {
	out := new(ResetPasswordResponse)
	err := c.cli.Invoke(ctx, UserService_ResetPassword_FullMethodName, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Logout(ctx context.Context, in *LogoutRequest) (*LogoutResponse, error) {
	out := new(LogoutResponse)
	err := c.cli.Invoke(ctx, UserService_Logout_FullMethodName, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) RefreshToken(ctx context.Context, in *RefreshTokenRequest) (*RefreshTokenResponse, error) {
	out := new(RefreshTokenResponse)
	err := c.cli.Invoke(ctx, UserService_RefreshToken_FullMethodName, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility.
type UserServiceServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	GetUserInfo(context.Context, *GetUserInfoRequest) (*GetUserInfoResponse, error)
	UpdateAvatar(context.Context, *UpdateAvatarRequest) (*UpdateAvatarResponse, error)
	ResetPassword(context.Context, *ResetPasswordRequest) (*ResetPasswordResponse, error)
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, fmt.Errorf("method Register not implemented")
}
func (UnimplementedUserServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, fmt.Errorf("method Login not implemented")
}
func (UnimplementedUserServiceServer) GetUserInfo(context.Context, *GetUserInfoRequest) (*GetUserInfoResponse, error) {
	return nil, fmt.Errorf("method GetUserInfo not implemented")
}
func (UnimplementedUserServiceServer) UpdateAvatar(context.Context, *UpdateAvatarRequest) (*UpdateAvatarResponse, error) {
	return nil, fmt.Errorf("method UpdateAvatar not implemented")
}
func (UnimplementedUserServiceServer) ResetPassword(context.Context, *ResetPasswordRequest) (*ResetPasswordResponse, error) {
	return nil, fmt.Errorf("method ResetPassword not implemented")
}
func (UnimplementedUserServiceServer) Logout(context.Context, *LogoutRequest) (*LogoutResponse, error) {
	return nil, fmt.Errorf("method Logout not implemented")
}
func (UnimplementedUserServiceServer) RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error) {
	return nil, fmt.Errorf("method RefreshToken not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}
func (UnimplementedUserServiceServer) testEmbeddedByValue()                     {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s zrpc.ServiceRegistrar, srv UserServiceServer) {
	// If the following call panics, it indicates UnimplementedUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, middleware zrpc.ServerMiddleware) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if middleware == nil {
		return srv.(UserServiceServer).Register(ctx, in)
	}
	info := &zrpc.ServerInfo{
		Server:     srv,
		FullMethod: UserService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return middleware(ctx, in, info, handler)
}

func _UserService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, middleware zrpc.ServerMiddleware) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if middleware == nil {
		return srv.(UserServiceServer).Login(ctx, in)
	}
	info := &zrpc.ServerInfo{
		Server:     srv,
		FullMethod: UserService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return middleware(ctx, in, info, handler)
}

func _UserService_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, middleware zrpc.ServerMiddleware) (interface{}, error) {
	in := new(GetUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if middleware == nil {
		return srv.(UserServiceServer).GetUserInfo(ctx, in)
	}
	info := &zrpc.ServerInfo{
		Server:     srv,
		FullMethod: UserService_GetUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserInfo(ctx, req.(*GetUserInfoRequest))
	}
	return middleware(ctx, in, info, handler)
}

func _UserService_UpdateAvatar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, middleware zrpc.ServerMiddleware) (interface{}, error) {
	in := new(UpdateAvatarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if middleware == nil {
		return srv.(UserServiceServer).UpdateAvatar(ctx, in)
	}
	info := &zrpc.ServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateAvatar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateAvatar(ctx, req.(*UpdateAvatarRequest))
	}
	return middleware(ctx, in, info, handler)
}

func _UserService_ResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, middleware zrpc.ServerMiddleware) (interface{}, error) {
	in := new(ResetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if middleware == nil {
		return srv.(UserServiceServer).ResetPassword(ctx, in)
	}
	info := &zrpc.ServerInfo{
		Server:     srv,
		FullMethod: UserService_ResetPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ResetPassword(ctx, req.(*ResetPasswordRequest))
	}
	return middleware(ctx, in, info, handler)
}

func _UserService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, middleware zrpc.ServerMiddleware) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if middleware == nil {
		return srv.(UserServiceServer).Logout(ctx, in)
	}
	info := &zrpc.ServerInfo{
		Server:     srv,
		FullMethod: UserService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Logout(ctx, req.(*LogoutRequest))
	}
	return middleware(ctx, in, info, handler)
}

func _UserService_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, middleware zrpc.ServerMiddleware) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if middleware == nil {
		return srv.(UserServiceServer).RefreshToken(ctx, in)
	}
	info := &zrpc.ServerInfo{
		Server:     srv,
		FullMethod: UserService_RefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RefreshToken(ctx, req.(*RefreshTokenRequest))
	}
	return middleware(ctx, in, info, handler)
}

// UserService_ServiceDesc is the zrpc.ServiceDesc for UserService service.
// It's only intended for direct use withzrpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = zrpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []zrpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _UserService_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _UserService_Login_Handler,
		},
		{
			MethodName: "GetUserInfo",
			Handler:    _UserService_GetUserInfo_Handler,
		},
		{
			MethodName: "UpdateAvatar",
			Handler:    _UserService_UpdateAvatar_Handler,
		},
		{
			MethodName: "ResetPassword",
			Handler:    _UserService_ResetPassword_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _UserService_Logout_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _UserService_RefreshToken_Handler,
		},
	},
	Metadata: "idl/user.proto",
}
