// Code generated by tool. DO NOT EDIT.
// app: goim, biz: auth

package errno

import (
	"github.com/crazyfrankie/zrpc-todolist/pkg/errorx/code"
)

const (
	ErrTokenInvalidCode              = 102101
	errTokenInvalidMessage           = ""
	errTokenInvalidNoAffectStability = true
)

func init() {

	code.Register(
		ErrTokenInvalidCode,
		errTokenInvalidMessage,
		code.WithAffectStability(!errTokenInvalidNoAffectStability),
	)

}
