// Code generated by tool. DO NOT EDIT.
// app: goim, biz: common

package errno

import (
	"github.com/crazyfrankie/zrpc-todolist/pkg/errorx/code"
)

const (
	ErrNoPermissionCode              = 103101
	errNoPermissionMessage           = ""
	errNoPermissionNoAffectStability = true
)

func init() {

	code.Register(
		ErrNoPermissionCode,
		errNoPermissionMessage,
		code.WithAffectStability(!errNoPermissionNoAffectStability),
	)

}
