// Code generated by tool. DO NOT EDIT.
// app: goim, biz: user

package errno

import (
	"github.com/crazyfrankie/zrpc-todolist/pkg/errorx/code"
)

const (
	ErrUserInvalidParamCode              = 101101
	errUserInvalidParamMessage           = ""
	errUserInvalidParamNoAffectStability = true

	ErrUserInfoInvalidCode              = 101102
	errUserInfoInvalidMessage           = ""
	errUserInfoInvalidNoAffectStability = true

	ErrUserEmailAlreadyExistCode              = 101103
	errUserEmailAlreadyExistMessage           = ""
	errUserEmailAlreadyExistNoAffectStability = true

	ErrUserUniqueNameAlreadyExistCode              = 101104
	errUserUniqueNameAlreadyExistMessage           = ""
	errUserUniqueNameAlreadyExistNoAffectStability = true
)

func init() {

	code.Register(
		ErrUserInvalidParamCode,
		errUserInvalidParamMessage,
		code.WithAffectStability(!errUserInvalidParamNoAffectStability),
	)

	code.Register(
		ErrUserInfoInvalidCode,
		errUserInfoInvalidMessage,
		code.WithAffectStability(!errUserInfoInvalidNoAffectStability),
	)

	code.Register(
		ErrUserEmailAlreadyExistCode,
		errUserEmailAlreadyExistMessage,
		code.WithAffectStability(!errUserEmailAlreadyExistNoAffectStability),
	)

	code.Register(
		ErrUserUniqueNameAlreadyExistCode,
		errUserUniqueNameAlreadyExistMessage,
		code.WithAffectStability(!errUserUniqueNameAlreadyExistNoAffectStability),
	)

}
