// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTask = "task"

// Task Task Table
type Task struct {
	ID        int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:Task ID" json:"id"`                                      // Task ID
	UserID    int64  `gorm:"column:user_id;not null;comment:Task OwnerID" json:"user_id"`                                            // Task OwnerID
	Title     string `gorm:"column:title;not null;comment:Task Title" json:"title"`                                                  // Task Title
	Content   string `gorm:"column:content;not null;comment:Task Content" json:"content"`                                            // Task Content
	Status    int32  `gorm:"column:status;not null;comment:Task Status" json:"status"`                                               // Task Status
	CreatedAt int64  `gorm:"column:created_at;not null;autoCreateTime:milli;comment:Creation Time (Milliseconds)" json:"created_at"` // Creation Time (Milliseconds)
	UpdatedAt int64  `gorm:"column:updated_at;not null;autoUpdateTime:milli;comment:Update Time (Milliseconds)" json:"updated_at"`   // Update Time (Milliseconds)
}

// TableName Task's table name
func (*Task) TableName() string {
	return TableNameTask
}
